
import PptxGenJS from "pptxgenjs";
import { Presentation } from "../types";

export const exportToPptx = async (presentation: Presentation) => {
  console.log("Starting PPTX Export...", presentation);
  
  try {
    const pptx = new PptxGenJS();
    
    pptx.layout = 'LAYOUT_16x9';
    pptx.title = presentation.title;
    pptx.author = "Visual Slides Generator";

    // Determine theme colors from visual guidelines
    const bgColor = presentation.visual_guidelines?.primary_color_scheme?.[0] || 'FFFFFF';
    const accentColor = presentation.visual_guidelines?.primary_color_scheme?.[1] || '0078D4';
    
    // Convert hex to PptxGenJS format (remove # if present)
    const cleanHex = (color: string) => color ? color.replace('#', '') : 'FFFFFF';
    const bgHex = cleanHex(bgColor);
    const accentHex = cleanHex(accentColor);
    const textHex = '000000'; // Default black text for white backgrounds

    // --- Title Slide ---
    const titleSlide = pptx.addSlide();
    titleSlide.background = { color: bgHex };
    
    // Main Title
    titleSlide.addText(presentation.title, { 
      x: 1, y: 2, w: '80%', h: 1.5, 
      fontSize: 44, bold: true, color: textHex, align: 'center', fontFace: 'Arial'
    });
    
    // Subtitle/Footer
    titleSlide.addText("Generated by Visual Slides AI", {
      x: 1, y: 3.5, w: '80%', h: 0.5,
      fontSize: 14, color: accentHex, align: 'center', fontFace: 'Arial'
    });

    // --- Content Slides ---
    for (const slide of presentation.slides) {
      const s = pptx.addSlide();
      s.background = { color: bgHex };
      
      // Header Bar
      s.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: '100%', h: 1.0, fill: { color: 'F3F4F6' } });
      
      // Slide Number
      s.addText(`${slide.slide_number}`, { x: 9.2, y: 0.3, w: 0.5, h: 0.4, fontSize: 12, color: '888888', align:'right' });

      // Slide Title
      s.addText(slide.title, { 
        x: 0.5, y: 0.2, w: '80%', h: 0.6, 
        fontSize: 24, bold: true, color: textHex, fontFace: 'Arial' 
      });

      // Content Layout
      if (slide.image_url) {
        // Layout with Image: Image on Left, Text on Right
        try {
          // Use 'path' for Data URLs in browser environment for better compatibility
          s.addImage({
              path: slide.image_url,
              x: 0.5, y: 1.5, w: 5.0, h: 2.81 // 16:9 ratio approx
          });
        } catch (e) {
          console.error(`Failed to add image to slide ${slide.slide_number}`, e);
        }

        // Text Content
        s.addText(slide.content, { 
          x: 5.8, y: 1.5, w: 3.8, h: 3.5, 
          fontSize: 16, color: textHex, fontFace: 'Arial', valign: 'top' 
        });

      } else {
        // Text Only Layout
        s.addText(slide.content, { 
          x: 0.5, y: 1.5, w: '90%', h: 4, 
          fontSize: 18, color: textHex, fontFace: 'Arial', valign: 'top' 
        });
      }

      // Speaker Notes
      if (slide.speaker_notes) {
          s.addNotes(slide.speaker_notes);
      }
    }

    // Save File
    const safeTitle = presentation.title.replace(/[^a-z0-9]/gi, '_').substring(0, 20);
    const fileName = `${safeTitle}_Presentation.pptx`;
    
    await pptx.writeFile({ fileName });
    console.log("PPTX Export Complete");
    
  } catch (err) {
    console.error("PPTX Export Critical Failure:", err);
    throw err;
  }
};
